name: Deploy DAG to GCP VM

on:
  push:
    branches:
      - main
    paths:
      - 'models/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'models/**/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        # service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Clear remote models directory
      run: |
        gcloud compute ssh airflow-poc --zone us-central1-a --command "rm -rf /home/dwiputra_rio/dbt-intro/models"

    - name: Copy files to GCP VM
      run: |
        gcloud compute scp --recurse ./models airflow-poc:/home/dwiputra_rio/dbt-intro/models --zone us-central1-a
