name: Deploy DAG to GCP VM

on:
  push:
    branches:
      - main
    paths:
      - 'models/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'models/**/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Copy files to GCP VM
      run: |
        gcloud compute scp ./models/* airflow-poc:/home/dwiputra_rio/dbt-intro/models --zone us-central1-a
